/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as USERUserRestaurentIdRouteImport } from './routes/(USER)/user/$restaurentId'
import { Route as RESTAURENTRestaurentDashboardRouteImport } from './routes/(RESTAURENT)/restaurent/dashboard'
import { Route as USERUserRestaurentIdIndexRouteImport } from './routes/(USER)/user/$restaurentId/index'
import { Route as USERUserRestaurentIdBrowsemenuRouteImport } from './routes/(USER)/user/$restaurentId/browsemenu'
import { Route as USERUserRestaurentIdItemIdRouteImport } from './routes/(USER)/user/$restaurentId/$itemId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const USERUserRestaurentIdRoute = USERUserRestaurentIdRouteImport.update({
  id: '/(USER)/user/$restaurentId',
  path: '/user/$restaurentId',
  getParentRoute: () => rootRouteImport,
} as any)
const RESTAURENTRestaurentDashboardRoute =
  RESTAURENTRestaurentDashboardRouteImport.update({
    id: '/(RESTAURENT)/restaurent/dashboard',
    path: '/restaurent/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const USERUserRestaurentIdIndexRoute =
  USERUserRestaurentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => USERUserRestaurentIdRoute,
  } as any)
const USERUserRestaurentIdBrowsemenuRoute =
  USERUserRestaurentIdBrowsemenuRouteImport.update({
    id: '/browsemenu',
    path: '/browsemenu',
    getParentRoute: () => USERUserRestaurentIdRoute,
  } as any)
const USERUserRestaurentIdItemIdRoute =
  USERUserRestaurentIdItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => USERUserRestaurentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/restaurent/dashboard': typeof RESTAURENTRestaurentDashboardRoute
  '/user/$restaurentId': typeof USERUserRestaurentIdRouteWithChildren
  '/user/$restaurentId/$itemId': typeof USERUserRestaurentIdItemIdRoute
  '/user/$restaurentId/browsemenu': typeof USERUserRestaurentIdBrowsemenuRoute
  '/user/$restaurentId/': typeof USERUserRestaurentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/restaurent/dashboard': typeof RESTAURENTRestaurentDashboardRoute
  '/user/$restaurentId/$itemId': typeof USERUserRestaurentIdItemIdRoute
  '/user/$restaurentId/browsemenu': typeof USERUserRestaurentIdBrowsemenuRoute
  '/user/$restaurentId': typeof USERUserRestaurentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(RESTAURENT)/restaurent/dashboard': typeof RESTAURENTRestaurentDashboardRoute
  '/(USER)/user/$restaurentId': typeof USERUserRestaurentIdRouteWithChildren
  '/(USER)/user/$restaurentId/$itemId': typeof USERUserRestaurentIdItemIdRoute
  '/(USER)/user/$restaurentId/browsemenu': typeof USERUserRestaurentIdBrowsemenuRoute
  '/(USER)/user/$restaurentId/': typeof USERUserRestaurentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/restaurent/dashboard'
    | '/user/$restaurentId'
    | '/user/$restaurentId/$itemId'
    | '/user/$restaurentId/browsemenu'
    | '/user/$restaurentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/restaurent/dashboard'
    | '/user/$restaurentId/$itemId'
    | '/user/$restaurentId/browsemenu'
    | '/user/$restaurentId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/(RESTAURENT)/restaurent/dashboard'
    | '/(USER)/user/$restaurentId'
    | '/(USER)/user/$restaurentId/$itemId'
    | '/(USER)/user/$restaurentId/browsemenu'
    | '/(USER)/user/$restaurentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RESTAURENTRestaurentDashboardRoute: typeof RESTAURENTRestaurentDashboardRoute
  USERUserRestaurentIdRoute: typeof USERUserRestaurentIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(USER)/user/$restaurentId': {
      id: '/(USER)/user/$restaurentId'
      path: '/user/$restaurentId'
      fullPath: '/user/$restaurentId'
      preLoaderRoute: typeof USERUserRestaurentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(RESTAURENT)/restaurent/dashboard': {
      id: '/(RESTAURENT)/restaurent/dashboard'
      path: '/restaurent/dashboard'
      fullPath: '/restaurent/dashboard'
      preLoaderRoute: typeof RESTAURENTRestaurentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(USER)/user/$restaurentId/': {
      id: '/(USER)/user/$restaurentId/'
      path: '/'
      fullPath: '/user/$restaurentId/'
      preLoaderRoute: typeof USERUserRestaurentIdIndexRouteImport
      parentRoute: typeof USERUserRestaurentIdRoute
    }
    '/(USER)/user/$restaurentId/browsemenu': {
      id: '/(USER)/user/$restaurentId/browsemenu'
      path: '/browsemenu'
      fullPath: '/user/$restaurentId/browsemenu'
      preLoaderRoute: typeof USERUserRestaurentIdBrowsemenuRouteImport
      parentRoute: typeof USERUserRestaurentIdRoute
    }
    '/(USER)/user/$restaurentId/$itemId': {
      id: '/(USER)/user/$restaurentId/$itemId'
      path: '/$itemId'
      fullPath: '/user/$restaurentId/$itemId'
      preLoaderRoute: typeof USERUserRestaurentIdItemIdRouteImport
      parentRoute: typeof USERUserRestaurentIdRoute
    }
  }
}

interface USERUserRestaurentIdRouteChildren {
  USERUserRestaurentIdItemIdRoute: typeof USERUserRestaurentIdItemIdRoute
  USERUserRestaurentIdBrowsemenuRoute: typeof USERUserRestaurentIdBrowsemenuRoute
  USERUserRestaurentIdIndexRoute: typeof USERUserRestaurentIdIndexRoute
}

const USERUserRestaurentIdRouteChildren: USERUserRestaurentIdRouteChildren = {
  USERUserRestaurentIdItemIdRoute: USERUserRestaurentIdItemIdRoute,
  USERUserRestaurentIdBrowsemenuRoute: USERUserRestaurentIdBrowsemenuRoute,
  USERUserRestaurentIdIndexRoute: USERUserRestaurentIdIndexRoute,
}

const USERUserRestaurentIdRouteWithChildren =
  USERUserRestaurentIdRoute._addFileChildren(USERUserRestaurentIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RESTAURENTRestaurentDashboardRoute: RESTAURENTRestaurentDashboardRoute,
  USERUserRestaurentIdRoute: USERUserRestaurentIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
