/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as USERUserRestaurentIdRouteImport } from './routes/(USER)/user/$restaurentId'
import { Route as RESTAURENTRestaurentDashboardRouteImport } from './routes/(RESTAURENT)/restaurent/dashboard'
import { Route as USERUserRestaurantIdIndexRouteImport } from './routes/(USER)/user/$restaurantId.index'
import { Route as USERUserRestaurantIdBrowsemenuRouteImport } from './routes/(USER)/user/$restaurantId.browsemenu'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const USERUserRestaurentIdRoute = USERUserRestaurentIdRouteImport.update({
  id: '/(USER)/user/$restaurentId',
  path: '/user/$restaurentId',
  getParentRoute: () => rootRouteImport,
} as any)
const RESTAURENTRestaurentDashboardRoute =
  RESTAURENTRestaurentDashboardRouteImport.update({
    id: '/(RESTAURENT)/restaurent/dashboard',
    path: '/restaurent/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const USERUserRestaurantIdIndexRoute =
  USERUserRestaurantIdIndexRouteImport.update({
    id: '/(USER)/user/$restaurantId/',
    path: '/user/$restaurantId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const USERUserRestaurantIdBrowsemenuRoute =
  USERUserRestaurantIdBrowsemenuRouteImport.update({
    id: '/(USER)/user/$restaurantId/browsemenu',
    path: '/user/$restaurantId/browsemenu',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/restaurent/dashboard': typeof RESTAURENTRestaurentDashboardRoute
  '/user/$restaurentId': typeof USERUserRestaurentIdRoute
  '/user/$restaurantId/browsemenu': typeof USERUserRestaurantIdBrowsemenuRoute
  '/user/$restaurantId/': typeof USERUserRestaurantIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/restaurent/dashboard': typeof RESTAURENTRestaurentDashboardRoute
  '/user/$restaurentId': typeof USERUserRestaurentIdRoute
  '/user/$restaurantId/browsemenu': typeof USERUserRestaurantIdBrowsemenuRoute
  '/user/$restaurantId': typeof USERUserRestaurantIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(RESTAURENT)/restaurent/dashboard': typeof RESTAURENTRestaurentDashboardRoute
  '/(USER)/user/$restaurentId': typeof USERUserRestaurentIdRoute
  '/(USER)/user/$restaurantId/browsemenu': typeof USERUserRestaurantIdBrowsemenuRoute
  '/(USER)/user/$restaurantId/': typeof USERUserRestaurantIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/restaurent/dashboard'
    | '/user/$restaurentId'
    | '/user/$restaurantId/browsemenu'
    | '/user/$restaurantId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/restaurent/dashboard'
    | '/user/$restaurentId'
    | '/user/$restaurantId/browsemenu'
    | '/user/$restaurantId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/(RESTAURENT)/restaurent/dashboard'
    | '/(USER)/user/$restaurentId'
    | '/(USER)/user/$restaurantId/browsemenu'
    | '/(USER)/user/$restaurantId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RESTAURENTRestaurentDashboardRoute: typeof RESTAURENTRestaurentDashboardRoute
  USERUserRestaurentIdRoute: typeof USERUserRestaurentIdRoute
  USERUserRestaurantIdBrowsemenuRoute: typeof USERUserRestaurantIdBrowsemenuRoute
  USERUserRestaurantIdIndexRoute: typeof USERUserRestaurantIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(USER)/user/$restaurentId': {
      id: '/(USER)/user/$restaurentId'
      path: '/user/$restaurentId'
      fullPath: '/user/$restaurentId'
      preLoaderRoute: typeof USERUserRestaurentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(RESTAURENT)/restaurent/dashboard': {
      id: '/(RESTAURENT)/restaurent/dashboard'
      path: '/restaurent/dashboard'
      fullPath: '/restaurent/dashboard'
      preLoaderRoute: typeof RESTAURENTRestaurentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(USER)/user/$restaurantId/': {
      id: '/(USER)/user/$restaurantId/'
      path: '/user/$restaurantId'
      fullPath: '/user/$restaurantId/'
      preLoaderRoute: typeof USERUserRestaurantIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(USER)/user/$restaurantId/browsemenu': {
      id: '/(USER)/user/$restaurantId/browsemenu'
      path: '/user/$restaurantId/browsemenu'
      fullPath: '/user/$restaurantId/browsemenu'
      preLoaderRoute: typeof USERUserRestaurantIdBrowsemenuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RESTAURENTRestaurentDashboardRoute: RESTAURENTRestaurentDashboardRoute,
  USERUserRestaurentIdRoute: USERUserRestaurentIdRoute,
  USERUserRestaurantIdBrowsemenuRoute: USERUserRestaurantIdBrowsemenuRoute,
  USERUserRestaurantIdIndexRoute: USERUserRestaurantIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
