/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RESTAURENTRestaurentRouteRouteImport } from './routes/(RESTAURENT)/restaurent/route'
import { Route as USERUserPaymentRouteImport } from './routes/(USER)/user/payment'
import { Route as USERUserOrderTrackingRouteImport } from './routes/(USER)/user/order-tracking'
import { Route as USERUserRestaurentIdRouteImport } from './routes/(USER)/user/$restaurentId'
import { Route as RESTAURENTRestaurentMenuManagerRouteImport } from './routes/(RESTAURENT)/restaurent/menu-manager'
import { Route as RESTAURENTRestaurentLiveOrdersRouteImport } from './routes/(RESTAURENT)/restaurent/live-orders'
import { Route as RESTAURENTRestaurentDashboardRouteImport } from './routes/(RESTAURENT)/restaurent/dashboard'
import { Route as RESTAURENTRestaurentAiInsightsRouteImport } from './routes/(RESTAURENT)/restaurent/ai-insights'
import { Route as USERUserRestaurentIdIndexRouteImport } from './routes/(USER)/user/$restaurentId/index'
import { Route as USERUserRestaurentIdBrowsemenuRouteImport } from './routes/(USER)/user/$restaurentId/browsemenu'
import { Route as USERUserRestaurentIdItemIdRouteImport } from './routes/(USER)/user/$restaurentId/$itemId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RESTAURENTRestaurentRouteRoute =
  RESTAURENTRestaurentRouteRouteImport.update({
    id: '/(RESTAURENT)/restaurent',
    path: '/restaurent',
    getParentRoute: () => rootRouteImport,
  } as any)
const USERUserPaymentRoute = USERUserPaymentRouteImport.update({
  id: '/(USER)/user/payment',
  path: '/user/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const USERUserOrderTrackingRoute = USERUserOrderTrackingRouteImport.update({
  id: '/(USER)/user/order-tracking',
  path: '/user/order-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const USERUserRestaurentIdRoute = USERUserRestaurentIdRouteImport.update({
  id: '/(USER)/user/$restaurentId',
  path: '/user/$restaurentId',
  getParentRoute: () => rootRouteImport,
} as any)
const RESTAURENTRestaurentMenuManagerRoute =
  RESTAURENTRestaurentMenuManagerRouteImport.update({
    id: '/menu-manager',
    path: '/menu-manager',
    getParentRoute: () => RESTAURENTRestaurentRouteRoute,
  } as any)
const RESTAURENTRestaurentLiveOrdersRoute =
  RESTAURENTRestaurentLiveOrdersRouteImport.update({
    id: '/live-orders',
    path: '/live-orders',
    getParentRoute: () => RESTAURENTRestaurentRouteRoute,
  } as any)
const RESTAURENTRestaurentDashboardRoute =
  RESTAURENTRestaurentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => RESTAURENTRestaurentRouteRoute,
  } as any)
const RESTAURENTRestaurentAiInsightsRoute =
  RESTAURENTRestaurentAiInsightsRouteImport.update({
    id: '/ai-insights',
    path: '/ai-insights',
    getParentRoute: () => RESTAURENTRestaurentRouteRoute,
  } as any)
const USERUserRestaurentIdIndexRoute =
  USERUserRestaurentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => USERUserRestaurentIdRoute,
  } as any)
const USERUserRestaurentIdBrowsemenuRoute =
  USERUserRestaurentIdBrowsemenuRouteImport.update({
    id: '/browsemenu',
    path: '/browsemenu',
    getParentRoute: () => USERUserRestaurentIdRoute,
  } as any)
const USERUserRestaurentIdItemIdRoute =
  USERUserRestaurentIdItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => USERUserRestaurentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/restaurent': typeof RESTAURENTRestaurentRouteRouteWithChildren
  '/restaurent/ai-insights': typeof RESTAURENTRestaurentAiInsightsRoute
  '/restaurent/dashboard': typeof RESTAURENTRestaurentDashboardRoute
  '/restaurent/live-orders': typeof RESTAURENTRestaurentLiveOrdersRoute
  '/restaurent/menu-manager': typeof RESTAURENTRestaurentMenuManagerRoute
  '/user/$restaurentId': typeof USERUserRestaurentIdRouteWithChildren
  '/user/order-tracking': typeof USERUserOrderTrackingRoute
  '/user/payment': typeof USERUserPaymentRoute
  '/user/$restaurentId/$itemId': typeof USERUserRestaurentIdItemIdRoute
  '/user/$restaurentId/browsemenu': typeof USERUserRestaurentIdBrowsemenuRoute
  '/user/$restaurentId/': typeof USERUserRestaurentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/restaurent': typeof RESTAURENTRestaurentRouteRouteWithChildren
  '/restaurent/ai-insights': typeof RESTAURENTRestaurentAiInsightsRoute
  '/restaurent/dashboard': typeof RESTAURENTRestaurentDashboardRoute
  '/restaurent/live-orders': typeof RESTAURENTRestaurentLiveOrdersRoute
  '/restaurent/menu-manager': typeof RESTAURENTRestaurentMenuManagerRoute
  '/user/order-tracking': typeof USERUserOrderTrackingRoute
  '/user/payment': typeof USERUserPaymentRoute
  '/user/$restaurentId/$itemId': typeof USERUserRestaurentIdItemIdRoute
  '/user/$restaurentId/browsemenu': typeof USERUserRestaurentIdBrowsemenuRoute
  '/user/$restaurentId': typeof USERUserRestaurentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(RESTAURENT)/restaurent': typeof RESTAURENTRestaurentRouteRouteWithChildren
  '/(RESTAURENT)/restaurent/ai-insights': typeof RESTAURENTRestaurentAiInsightsRoute
  '/(RESTAURENT)/restaurent/dashboard': typeof RESTAURENTRestaurentDashboardRoute
  '/(RESTAURENT)/restaurent/live-orders': typeof RESTAURENTRestaurentLiveOrdersRoute
  '/(RESTAURENT)/restaurent/menu-manager': typeof RESTAURENTRestaurentMenuManagerRoute
  '/(USER)/user/$restaurentId': typeof USERUserRestaurentIdRouteWithChildren
  '/(USER)/user/order-tracking': typeof USERUserOrderTrackingRoute
  '/(USER)/user/payment': typeof USERUserPaymentRoute
  '/(USER)/user/$restaurentId/$itemId': typeof USERUserRestaurentIdItemIdRoute
  '/(USER)/user/$restaurentId/browsemenu': typeof USERUserRestaurentIdBrowsemenuRoute
  '/(USER)/user/$restaurentId/': typeof USERUserRestaurentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/restaurent'
    | '/restaurent/ai-insights'
    | '/restaurent/dashboard'
    | '/restaurent/live-orders'
    | '/restaurent/menu-manager'
    | '/user/$restaurentId'
    | '/user/order-tracking'
    | '/user/payment'
    | '/user/$restaurentId/$itemId'
    | '/user/$restaurentId/browsemenu'
    | '/user/$restaurentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/restaurent'
    | '/restaurent/ai-insights'
    | '/restaurent/dashboard'
    | '/restaurent/live-orders'
    | '/restaurent/menu-manager'
    | '/user/order-tracking'
    | '/user/payment'
    | '/user/$restaurentId/$itemId'
    | '/user/$restaurentId/browsemenu'
    | '/user/$restaurentId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/(RESTAURENT)/restaurent'
    | '/(RESTAURENT)/restaurent/ai-insights'
    | '/(RESTAURENT)/restaurent/dashboard'
    | '/(RESTAURENT)/restaurent/live-orders'
    | '/(RESTAURENT)/restaurent/menu-manager'
    | '/(USER)/user/$restaurentId'
    | '/(USER)/user/order-tracking'
    | '/(USER)/user/payment'
    | '/(USER)/user/$restaurentId/$itemId'
    | '/(USER)/user/$restaurentId/browsemenu'
    | '/(USER)/user/$restaurentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RESTAURENTRestaurentRouteRoute: typeof RESTAURENTRestaurentRouteRouteWithChildren
  USERUserRestaurentIdRoute: typeof USERUserRestaurentIdRouteWithChildren
  USERUserOrderTrackingRoute: typeof USERUserOrderTrackingRoute
  USERUserPaymentRoute: typeof USERUserPaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(RESTAURENT)/restaurent': {
      id: '/(RESTAURENT)/restaurent'
      path: '/restaurent'
      fullPath: '/restaurent'
      preLoaderRoute: typeof RESTAURENTRestaurentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(USER)/user/payment': {
      id: '/(USER)/user/payment'
      path: '/user/payment'
      fullPath: '/user/payment'
      preLoaderRoute: typeof USERUserPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(USER)/user/order-tracking': {
      id: '/(USER)/user/order-tracking'
      path: '/user/order-tracking'
      fullPath: '/user/order-tracking'
      preLoaderRoute: typeof USERUserOrderTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(USER)/user/$restaurentId': {
      id: '/(USER)/user/$restaurentId'
      path: '/user/$restaurentId'
      fullPath: '/user/$restaurentId'
      preLoaderRoute: typeof USERUserRestaurentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(RESTAURENT)/restaurent/menu-manager': {
      id: '/(RESTAURENT)/restaurent/menu-manager'
      path: '/menu-manager'
      fullPath: '/restaurent/menu-manager'
      preLoaderRoute: typeof RESTAURENTRestaurentMenuManagerRouteImport
      parentRoute: typeof RESTAURENTRestaurentRouteRoute
    }
    '/(RESTAURENT)/restaurent/live-orders': {
      id: '/(RESTAURENT)/restaurent/live-orders'
      path: '/live-orders'
      fullPath: '/restaurent/live-orders'
      preLoaderRoute: typeof RESTAURENTRestaurentLiveOrdersRouteImport
      parentRoute: typeof RESTAURENTRestaurentRouteRoute
    }
    '/(RESTAURENT)/restaurent/dashboard': {
      id: '/(RESTAURENT)/restaurent/dashboard'
      path: '/dashboard'
      fullPath: '/restaurent/dashboard'
      preLoaderRoute: typeof RESTAURENTRestaurentDashboardRouteImport
      parentRoute: typeof RESTAURENTRestaurentRouteRoute
    }
    '/(RESTAURENT)/restaurent/ai-insights': {
      id: '/(RESTAURENT)/restaurent/ai-insights'
      path: '/ai-insights'
      fullPath: '/restaurent/ai-insights'
      preLoaderRoute: typeof RESTAURENTRestaurentAiInsightsRouteImport
      parentRoute: typeof RESTAURENTRestaurentRouteRoute
    }
    '/(USER)/user/$restaurentId/': {
      id: '/(USER)/user/$restaurentId/'
      path: '/'
      fullPath: '/user/$restaurentId/'
      preLoaderRoute: typeof USERUserRestaurentIdIndexRouteImport
      parentRoute: typeof USERUserRestaurentIdRoute
    }
    '/(USER)/user/$restaurentId/browsemenu': {
      id: '/(USER)/user/$restaurentId/browsemenu'
      path: '/browsemenu'
      fullPath: '/user/$restaurentId/browsemenu'
      preLoaderRoute: typeof USERUserRestaurentIdBrowsemenuRouteImport
      parentRoute: typeof USERUserRestaurentIdRoute
    }
    '/(USER)/user/$restaurentId/$itemId': {
      id: '/(USER)/user/$restaurentId/$itemId'
      path: '/$itemId'
      fullPath: '/user/$restaurentId/$itemId'
      preLoaderRoute: typeof USERUserRestaurentIdItemIdRouteImport
      parentRoute: typeof USERUserRestaurentIdRoute
    }
  }
}

interface RESTAURENTRestaurentRouteRouteChildren {
  RESTAURENTRestaurentAiInsightsRoute: typeof RESTAURENTRestaurentAiInsightsRoute
  RESTAURENTRestaurentDashboardRoute: typeof RESTAURENTRestaurentDashboardRoute
  RESTAURENTRestaurentLiveOrdersRoute: typeof RESTAURENTRestaurentLiveOrdersRoute
  RESTAURENTRestaurentMenuManagerRoute: typeof RESTAURENTRestaurentMenuManagerRoute
}

const RESTAURENTRestaurentRouteRouteChildren: RESTAURENTRestaurentRouteRouteChildren =
  {
    RESTAURENTRestaurentAiInsightsRoute: RESTAURENTRestaurentAiInsightsRoute,
    RESTAURENTRestaurentDashboardRoute: RESTAURENTRestaurentDashboardRoute,
    RESTAURENTRestaurentLiveOrdersRoute: RESTAURENTRestaurentLiveOrdersRoute,
    RESTAURENTRestaurentMenuManagerRoute: RESTAURENTRestaurentMenuManagerRoute,
  }

const RESTAURENTRestaurentRouteRouteWithChildren =
  RESTAURENTRestaurentRouteRoute._addFileChildren(
    RESTAURENTRestaurentRouteRouteChildren,
  )

interface USERUserRestaurentIdRouteChildren {
  USERUserRestaurentIdItemIdRoute: typeof USERUserRestaurentIdItemIdRoute
  USERUserRestaurentIdBrowsemenuRoute: typeof USERUserRestaurentIdBrowsemenuRoute
  USERUserRestaurentIdIndexRoute: typeof USERUserRestaurentIdIndexRoute
}

const USERUserRestaurentIdRouteChildren: USERUserRestaurentIdRouteChildren = {
  USERUserRestaurentIdItemIdRoute: USERUserRestaurentIdItemIdRoute,
  USERUserRestaurentIdBrowsemenuRoute: USERUserRestaurentIdBrowsemenuRoute,
  USERUserRestaurentIdIndexRoute: USERUserRestaurentIdIndexRoute,
}

const USERUserRestaurentIdRouteWithChildren =
  USERUserRestaurentIdRoute._addFileChildren(USERUserRestaurentIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RESTAURENTRestaurentRouteRoute: RESTAURENTRestaurentRouteRouteWithChildren,
  USERUserRestaurentIdRoute: USERUserRestaurentIdRouteWithChildren,
  USERUserOrderTrackingRoute: USERUserOrderTrackingRoute,
  USERUserPaymentRoute: USERUserPaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
